### ISSUE TITLE
CIIP_DATALOADER NOT FOUND!

### ISSUE THREAD

**Issue by NandiniLReddy** [AlessandroW/A-Knee-Cannot-Have-Lunge-Disease-Out-Of-Distribution-Detection-With-In-Distribution-Voting#1]
could not find the cache_dir, from which we couldn't get the ciip_dataloader.

Could you please give us more information about the cache_dir??

**Comment by AlessandroW** [comment]
Hi, this was an internal data loader to load the files from disk, with caching.

You just need to download the original datasets. From there it should be clear what the data module expects.
